### ISSUE TITLE
Test the crate in all configurations

### ISSUE THREAD

**Issue by vbfox** [instructure/paseto#25]
Issue creation requested here: https://github.com/instructure/paseto/pull/23#issuecomment-590089113

There are currently 3 features that can be disabled and all possible combinations should be checked that they build & pass test during CI.

**Comment by Mythra** [comment]
Hey, 

First off sorry about the in general delay of this crate. With the crazy year that is 2020, and back and forth of a company I'm no longer at. This wasn't handled ideally in anyway I would've been close to liking. Anyway there are now tests on every PR + branch for every configuration.

Sorry again for the delay.
