### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by rdaum** [instructure/paseto#62]
I evaluated 3 PASETO implementations in Rust and found the API on this one to be most ergonomic and featureful.

But I see there has not been any update in 2 years, the Cargo.toml shows a 3.0.0 release but that's not what's on Crates.io, and 'cargo deny' is complaining about EOL on the `failure` crate brought in as a dep for 2.0.0.

I  also see a few automatic PRs  in the queue here, unmerged.

I guess I'm wondering if there's a plan on this project. I'd offer to help out a bit, but I'm no PASETO (or auth/security) expert.

**Comment by Mythra** [comment]
Hey @rdaum ,

Unfortunately I do not have the bandwidth to maintain this anymore, and I believe it's usages at Inst have all been moved on from at this point. Considering it's now getting suspicious looking PRs, I'm just going to archive the repository. You should be able to fork it and continue if you'd like.

I'd probably personally switch or contribute to: https://github.com/brycx/pasetors , as I was never able to put in the time for the V3/V4 split, and our APIs would've had to change to become more like this (adding in type traits and the like) to help prevent misuse more. I'm sure brycx might also like the contributors 😄 

Thanks,
Cynthia
